### ISSUE TITLE
blink_led.rb does not run with ruby 2.2

### ISSUE THREAD

**Issue by zankich** [hybridgroup/ruby-firmata#9]
I get this error while trying to run the `blink_led.rb` program with ruby 2.2, but ruby 2.1.4 works fine.

```bash
$ bundle exec ruby examples/blink_led.rb 
/home/adrian/code/hybridgroup/ruby-firmata/lib/firmata/board.rb:443:in `trap': Invalid argument - SIGKILL (Errno::EINVAL)
        from /home/adrian/code/hybridgroup/ruby-firmata/lib/firmata/board.rb:443:in `block in trap_signals'
        from /home/adrian/code/hybridgroup/ruby-firmata/lib/firmata/board.rb:442:in `each'
        from /home/adrian/code/hybridgroup/ruby-firmata/lib/firmata/board.rb:442:in `trap_signals'
        from /home/adrian/code/hybridgroup/ruby-firmata/lib/firmata/board.rb:42:in `initialize'
        from examples/blink_led.rb:9:in `new'
        from examples/blink_led.rb:9:in `<main>'
```

**Comment by iTSangar** [comment]
Same error here:

Mac OSX: v10.10.4
Ruby: v 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14] using rvm
Artoo: v1.8.1
Artoo-arduino: v1.4.4
Gort: v0.3.0

Log:

```
I, [2015-06-05T03:44:07.008606 #20510]  INFO -- : Registering connection 'firmata'...
I, [2015-06-05T03:44:07.008679 #20510]  INFO -- : Registering device 'led'...
I, [2015-06-05T03:44:07.008705 #20510]  INFO -- : Preparing work...
I, [2015-06-05T03:44:07.009492 #20510]  INFO -- : Initializing artoo::connection firmata...
I, [2015-06-05T03:44:07.019735 #20510]  INFO -- : Initializing artoo::device led...
I, [2015-06-05T03:44:07.022083 #20510]  INFO -- : Starting work...
I, [2015-06-05T03:44:07.022284 #20510]  INFO -- : Connecting to 'firmata' on port '/dev/cu.usbmodem1421'...
E, [2015-06-05T03:44:07.185892 #20510] ERROR -- : Invalid argument - SIGKILL
E, [2015-06-05T03:44:07.185980 #20510] ERROR -- : ["/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:443:in `trap'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:443:in `block in trap_signals'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:442:in `each'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:442:in `trap_signals'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:42:in `initialize'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/artoo-arduino-1.4.4/lib/artoo/adaptors/firmata.rb:15:in `new'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/artoo-arduino-1.4.4/lib/artoo/adaptors/firmata.rb:15:in `connect'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'", "(celluloid):0:in `remote procedure call'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/artoo-1.8.1/lib/artoo/connection.rb:35:in `connect'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'", "/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'"]
E, [2015-06-05T03:44:07.186076 #20510] ERROR -- : Actor crashed!
Errno::EINVAL: Invalid argument - SIGKILL
	/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:443:in `trap'
	/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:443:in `block in trap_signals'
	/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:442:in `each'
	/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:442:in `trap_signals'
	/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/hybridgroup-firmata-0.4.6/lib/firmata/board.rb:42:in `initialize'
	/Users/iTSangar/.rvm/gems/ruby-2.2.0/gems/artoo-arduino-1.4.4/lib/artoo/adaptors/firmata.rb:15:in `new'

continue..
```

**Comment by Jesterovskiy** [comment]
Same for me, but as I  understood HybridGroup team now contributing mostly in Cylon project. @zankich  am I right?

**Comment by deadprogram** [comment]
I'll take a look at this. True have been spending a lot of time on Cylon.js but Artoo keeps going too.
